### ISSUE TITLE
Fresh system script fails on macOS 12.3

### ISSUE THREAD

**Issue by sandeep-sen** [psox/psoxizsh#8]
OS: macOS 12.3 Monterey
Processor: Apple Silicon M1 Pro
Memory: 32 GB

Steps to reproduce:
1. Install Homebrew
2. Install iterm2 via Homebrew
3. Install tmux via Homebrew
4. Install NeoVim via Homebrew
5. Git clone the project `git clone --recurse-submodules --recursive https://github.com/psox/psoxizsh.git ~/.psoxizsh`
6. Run fresh system script for the current user `~/.psoxizsh/fresh-system`

Output:
```
install: illegal option -- -
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
```

**After restarting iterm it looks like the install worked**
<img width="1137" alt="Screen Shot 2022-03-29 at 9 26 33 PM" src="https://user-images.githubusercontent.com/26223141/160751295-7a8ab32a-3556-4cb6-b8db-b84865d4c492.png">

**Comment by psox** [comment]
macOS `install` does not support the long form of  the `--mode` argument.  

Updated to use the short form `-m`
